# Generated by Django 3.1 on 2020-08-29 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('logo', models.ImageField(upload_to='company_images')),
                ('description', models.TextField(blank=True, default='')),
                ('employee_count', models.IntegerField(default=0, null=True)),
                ('owner',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('NOT_LOOKING_FOR_JOB', 'Не ищу работу'),
                                                     ('CONSIDERING_PROPOSALS', 'Рассматриваю предложения'),
                                                     ('LOOKING_FOR_JOB', 'Ищу работу')], max_length=21)),
                ('salary', models.IntegerField()),
                ('specialty', models.CharField(max_length=35)),
                ('grade', models.CharField(
                    choices=[('TRAINEE', 'Стажер'), ('JUNIOR', 'Стажер'), ('MIDDLE', 'Миддл'), ('SENOR', 'Сеньор'),
                             ('LEAD', 'ЛИД')], max_length=7)),
                ('education', models.CharField(max_length=250)),
                ('experience', models.TextField()),
                ('portfolio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20, unique=True)),
                ('title', models.CharField(default='', max_length=40)),
                ('picture', models.ImageField(upload_to='speciality_images')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('skills', models.TextField(default='')),
                ('description', models.TextField()),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('published_at', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies',
                                              to='vacancies.company')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies',
                                                to='vacancies.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=20)),
                ('written_phone', models.PositiveIntegerField()),
                ('written_cover_letter', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications',
                                           to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications',
                                              to='vacancies.vacancy')),
            ],
        ),
    ]
